services:
  match3-app:
    build: .
    container_name: match3_mmo_prod
    # Монтируем том для сохранения БД
    volumes:
      - ./match3.db:/app/match3.db
      # Для Linux X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri
      - /dev/snd
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    restart: unless-stopped